### ISSUE TITLE
Update action to Node v20?

### ISSUE THREAD

**Issue by jbwharris** [paxha/cpanel-deploy#1]
I just tried this and got an error about needing to upgrade to Node 20 from 16. Are you planning on updating it?

**Comment by paxha** [comment]
This is warning, not error. if you can upgrade you can open a PR.

**Comment by Henriquecsh** [comment]
I'm also receiving an error, it's no longer an alert.

**Comment by paxha** [comment]
v4 added.

**Comment by Henriquecsh** [comment]
Thank you

**Comment by Henriquecsh** [comment]
I don't have success with v4.
![image](https://github.com/user-attachments/assets/ec26b6b3-cfee-48d6-95cf-08211406c6a5)

**Comment by paxha** [comment]
try v4.0

**Comment by paxha** [comment]
- name: cPanel Deploy using API Token
                uses: paxha/cpanel-deploy@v4.0

**Comment by jbwharris** [comment]
I keep getting this error when running this action. Any idea what I might be doing wrong here?

```

Run paxha/cpanel-deploy@v4.0
Starting deployment...
baseUrl: ***:2083/execute/
Deployment finished successfully
Branch main updated successfully
deploy: true
TypeError: Cannot read properties of null (reading 'task_id')
    at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33338:63
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357
                        throw new Error(error);
                              ^

Error: TypeError: Cannot read properties of null (reading 'task_id')
    at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.13.1
```

![image](https://github.com/user-attachments/assets/3f7a6aa7-ca18-4ed0-a148-a08d89936063)

**Comment by paxha** [comment]
can you share your `cpanel.yml` file?

**Comment by jbwharris** [comment]
@paxha https://github.com/jbwharris/scrobblerad.io/blob/main/.github/workflows/cpanel-deploy.yml

I've double checked all my secrets. I don't get why it's messing up. I've tried yours and this one https://github.com/pinkasey/cpanel-deploy-action and get the same issue.

**Comment by paxha** [comment]
it means the issue is in CPanel's apis. Because when the package is developed it was working fine.

**Comment by CallumME** [comment]
@jbwharris did you ever find a solution to this? was it something to do with your .cpanel.yml file?

**Comment by jbwharris** [comment]
> [@jbwharris](https://github.com/jbwharris) did you ever find a solution to this? was it something to do with your .cpanel.yml file?

I never truly found a solution. I'm actually hashing through it again with my host at the moment. I'll update if I do manage to get it working. It's always been tricky because my host doesn't want to get involved with debugging development issues, but just pointing to the standard cPanel documentation doesn't really do too many favours either since they're generic and don't really show implicit working code for my particular host.

**Comment by david-ortegac** [comment]
> I keep getting this error when running this action. Any idea what I might be doing wrong here?
> 
> ```
> 
> Run paxha/cpanel-deploy@v4.0
> Starting deployment...
> baseUrl: ***:2083/execute/
> Deployment finished successfully
> Branch main updated successfully
> deploy: true
> TypeError: Cannot read properties of null (reading 'task_id')
>     at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33338:63
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357
>                         throw new Error(error);
>                               ^
> 
> Error: TypeError: Cannot read properties of null (reading 'task_id')
>     at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357:31
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v20.13.1
> ```
> 
> ![image](https://github.com/user-attachments/assets/3f7a6aa7-ca18-4ed0-a148-a08d89936063)

I've same error

TypeError: Cannot read properties of null (reading 'task_id')
    at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33338:63
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357
                        throw new Error(error);
                              ^

Error: TypeError: Cannot read properties of null (reading 'task_id')
    at /home/runner/work/_actions/paxha/cpanel-deploy/v4.0/dist/index.js:33357:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
